spring.application.name=desdeaqui
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/desdeaqui
spring.datasource.username=root
spring.datasource.password=Root123_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.sql.init.mode=never